apiVersion: v1
kind: Service
metadata:
  name: observium-np
  #namespace: observium
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  - port: 8443
    name: https
  selector:
    app: observium