apiVersion: v1
kind: Service
metadata:
  name: observium-lb
  #namespace: observium
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    name: http
  - port: 8443
    targetPort: 443
    name: https
  selector:
    app: observium